=== vernetya/wdms2prod/res/schemas/master-data/Play.1.0.0.json
{
  "x-osdu-license": "Copyright 2022, The Open Group \\nLicensed under the Apache License, Version 2.0 (the \"License\"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.",
  "$id": "https://schema.osdu.opengroup.org/json/master-data/Play.1.0.0.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "x-osdu-schema-source": "osdu:wks:master-data--Play:1.0.0",
  "title": "Play",
  "description": "A named area that likely contains a combination of certain geological factors making it prospective for mineral exploration. It is often considered to be a set of prospects with a common set of characteristics.",
  "type": "object",
  "properties": {
    "id": {
      "description": "Previously called ResourceID or SRN which identifies this OSDU resource object without version.",
      "title": "Entity ID",
      "type": "string",
      "pattern": "^[\\w\\-\\.]+:master-data\\-\\-Play:[\\w\\-\\.\\:\\%]+$",
      "example": "namespace:master-data--Play:e39ac112-8182-5814-91f2-5c7a43518897"
    },
    "kind": {
      "description": "The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.",
      "title": "Entity Kind",
      "type": "string",
      "pattern": "^[\\w\\-\\.]+:[\\w\\-\\.]+:[\\w\\-\\.]+:[0-9]+.[0-9]+.[0-9]+$",
      "example": "osdu:wks:master-data--Play:1.0.0"
    },
    "version": {
      "description": "The version number of this OSDU resource; set by the framework.",
      "title": "Version Number",
      "type": "integer",
      "format": "int64",
      "example": 1562066009929332
    },
    "acl": {
      "description": "The access control tags associated with this entity.",
      "title": "Access Control List",
      "$ref": "../abstract/AbstractAccessControlList.1.0.0.json"
    },
    "legal": {
      "description": "The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.",
      "title": "Legal Tags",
      "$ref": "../abstract/AbstractLegalTags.1.0.0.json"
    },
    "tags": {
      "title": "Tag Dictionary",
      "description": "A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "example": {
        "NameOfKey": "String value"
      }
    },
    "createTime": {
      "description": "Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.",
      "title": "Resource Object Creation DateTime",
      "type": "string",
      "format": "date-time",
      "example": "2020-12-16T11:46:20.163Z"
    },
    "createUser": {
      "title": "Resource Object Creation User Reference",
      "description": "The user reference, which created the first version of this resource object. Set by the System.",
      "type": "string",
      "example": "some-user@some-company-cloud.com"
    },
    "modifyTime": {
      "description": "Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.",
      "title": "Resource Object Version Creation DateTime",
      "type": "string",
      "format": "date-time",
      "example": "2020-12-16T11:52:24.477Z"
    },
    "modifyUser": {
      "title": "Resource Object Version Creation User Reference",
      "description": "The user reference, which created this version of this resource object. Set by the System.",
      "type": "string",
      "example": "some-user@some-company-cloud.com"
    },
    "ancestry": {
      "description": "The links to data, which constitute the inputs, from which this record instance is derived.",
      "title": "Ancestry",
      "$ref": "../abstract/AbstractLegalParentList.1.0.0.json"
    },
    "meta": {
      "description": "The Frame of Reference meta data section linking the named properties to self-contained definitions.",
      "title": "Frame of Reference Meta Data",
      "type": "array",
      "items": {
        "$ref": "../abstract/AbstractMetaItem.1.0.0.json"
      }
    },
    "data": {
      "allOf": [
        {
          "$ref": "../abstract/AbstractCommonResources.1.0.0.json"
        },
        {
          "$ref": "../abstract/AbstractMaster.1.0.0.json"
        },
        {
          "type": "object",
          "properties": {
            "PlayID": {
              "type": "string",
              "title": "External Play Identifier",
              "description": "Native identifier from a Master Data Management System or other trusted source external to OSDU - stored here in order to allow for multi-system connection and synchronization. If used, the \"Source\" property should identify that source system."
            },
            "PlayName": {
              "type": "string",
              "description": "Preferred name for a Play."
            },
            "PlayNameAliases": {
              "type": "array",
              "description": "DEPRECATED: please use data.NameAliases. Set of alternative names for a Play.",
              "items": {
                "$ref": "../abstract/AbstractAliasNames.1.0.0.json"
              }
            },
            "PlayDescription": {
              "type": "string",
              "description": "Textual description about a Play."
            },
            "EffectiveDate": {
              "type": "string",
              "description": "Date when a Play goes into effect.",
              "format": "date-time",
              "x-osdu-frame-of-reference": "DateTime"
            },
            "TerminationDate": {
              "type": "string",
              "description": "Date when a Play is no longer in effect.",
              "format": "date-time",
              "x-osdu-frame-of-reference": "DateTime"
            },
            "PlayTypeID": {
              "type": "string",
              "title": "Play Type ID",
              "description": "The type of play as defined in PlayType.",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-PlayType:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "GroupType": "reference-data",
                  "EntityType": "PlayType"
                }
              ]
            }
          },
          "title": "IndividualProperties"
        },
        {
          "type": "object",
          "properties": {
            "ExtensionProperties": {
              "type": "object"
            }
          },
          "title": "ExtensionProperties"
        }
      ]
    }
  },
  "required": [
    "kind",
    "acl",
    "legal"
  ],
  "additionalProperties": false,
  "x-osdu-review-status": "Accepted",
  "x-osdu-virtual-properties": {
    "data.VirtualProperties.DefaultLocation": {
      "type": "object",
      "priority": [
        {
          "path": "data.SpatialLocation"
        }
      ]
    },
    "data.VirtualProperties.DefaultName": {
      "type": "string",
      "priority": [
        {
          "path": "data.PlayName"
        }
      ]
    }
  },
  "x-osdu-inheriting-from-kind": []
}

=== vernetya/wdms2prod/res/examples/wellLog_v3_120.json
{
    "acl": {
        "viewers": [
            "data.default.viewers@opendes.com"
        ],
        "owners": [
            "data.default.owners@opendes.com"
        ]
    },
    "data": {
        "Curves": [
            {
                "CurveID": "GR_ID",
                "Mnemonic": "GR",
                "CurveUnit": "opendes:reference-data--UnitOfMeasure:m:",
                "LogCurveFamilyID": "opendes:reference-data--LogCurveFamily:GammaRay:",
                "NumberOfColumns": 1,
                "CurveDescription": "Gamma Ray",
                "CurveSampleTypeID": "opendes:reference-data--CurveSampleType:float:"
            },
            {
                "CurveID": "POR_ID",
                "Mnemonic": "NPOR",
                "CurveUnit": "opendes:reference-data--UnitOfMeasure:m:",
                "LogCurveFamilyID": "opendes:reference-data--LogCurveFamily:NeutronPorosity:",
                "NumberOfColumns": 1,
                "CurveDescription": "Neutron Porosity",
                "CurveSampleTypeID": "opendes:reference-data--CurveSampleType:float:"
            },
            {
                "CurveID": "Bulk Density",
                "Mnemonic": "RHOB",
                "CurveUnit": "opendes:reference-data--UnitOfMeasure:m:",
                "LogCurveFamilyID": "opendes:reference-data--LogCurveFamily:BulkDensity:",
                "CurveSampleTypeID": "opendes:reference-data--CurveSampleType:float:"
            }
        ],
        "WellboreID": "opendes:master-data--Wellbore:123456:",
        "CreationDateTime": "2013-03-22T11:16:03Z",
        "VerticalMeasurement": {
            "VerticalMeasurement": 2680.5,
            "VerticalMeasurementPathID": "opendes:reference-data--VerticalMeasurementPath:MD:",
            "VerticalMeasurementUnitOfMeasureID": "opendes:reference-data--UnitOfMeasure:ft:"
        },
        "TopMeasuredDepth": 12345.6,
        "BottomMeasuredDepth": 13856.2,
        "Name": "welllogName",

        "SamplingDomainTypeID": "opendes:reference-data--WellLogSamplingDomainType:Depth:",
        "IsRegular": true,
        "LogRemark": "example data for API documentation",
        "SamplingInterval": 0.1

    },
    "id": "opendes:work-product-component--WellLog:123456",
    "kind": "osdu:wks:work-product-component--WellLog:1.2.0",
    "legal": {
        "legaltags": [
            "legaltags"
        ],
        "otherRelevantDataCountries": [
            "US",
            "FR"
        ]
    },
    "meta": [{
            "kind": "Unit",
            "name": "ft",
            "persistableReference": "{\"scaleOffset\":{\"scale\":0.3048,\"offset\":0.0},\"symbol\":\"ft\",\"baseMeasurement\":{\"ancestry\":\"Length\",\"type\":\"UM\"},\"type\":\"USO\"}",
            "propertyNames": [
                "TopMeasuredDepth",
                "BottomMeasuredDepth",
                "SamplingInterval"
            ],
            "propertyValues": [
                "ft"
            ]
        }, {
            "kind": "DateTime",
            "name": "datetime",
            "persistableReference": "{\"format\":\"yyyy-MM-ddTHH:mm:ssZ\",\"timeZone\":\"UTC\",\"type\":\"DTM\"}",
            "propertyNames": [
                "dateModified",
                "dateCreated"
            ]
        }
    ]
}
